### ISSUE TITLE
Error invoking SVGAnalyzer

### ISSUE THREAD

**Issue by itsnatscott** [aurelia/pal#19]
SUPPORT REQUESTS/QUESTIONS:

**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Linux , Ubuntu(14.04)

* **Node Version:**
7.0.0

* **NPM Version:**
3.10.8

* **JSPM OR Webpack AND Version**
Webpack 2.1.0-beta.22
on Application, neither webpack nor jspm on the components library

* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
all | TypeScript X.X | ESNext

**Current behavior:**
 I have my application running in one repository using webpack, and I have a reusable components library in a different repo that has neither jspm nor webpack. It is linked to the main application using npm link and being referenced as any node_module would.

Using bindable in my components however causes this error: 
```Inner Error:
Message: _aureliaPal.DOM.createElement is not a function
Inner Error Stack:
TypeError: _aureliaPal.DOM.createElement is not a function
    at createElement (http://localhost:9000/app.bundle.js:104267:29)
    at new SVGAnalyzer (http://localhost:9000/app.bundle.js:104270:9)
    at Object.invoke (http://localhost:9000/aurelia-bootstrap.bundle.js:8470:12)
    at InvocationHandler.invoke (http://localhost:9000/aurelia-bootstrap.bundle.js:8447:166)
    at Container.invoke (http://localhost:9000/aurelia-bootstrap.bundle.js:8700:23)
    at StrategyResolver.get (http://localhost:9000/aurelia-bootstrap.bundle.js:8175:35)
    at Container.get (http://localhost:9000/aurelia-bootstrap.bundle.js:8633:39)
    at Object.invoke (http://localhost:9000/aurelia-bootstrap.bundle.js:8500:103)
    at InvocationHandler.invoke (http://localhost:9000/aurelia-bootstrap.bundle.js:8447:166)
    at Container.invoke (http://localhost:9000/aurelia-bootstrap.bundle.js:8700:23)
    at StrategyResolver.get (http://localhost:9000/aurelia-bootstrap.bundle.js:8175:35)
    at Container.get (http://localhost:9000/aurelia-bootstrap.bundle.js:8633:39)
    at HtmlBehaviorResource.initialize (http://localhost:9000/app.bundle.js:109356:106)
    at ResourceDescription.initialize (http://localhost:9000/aurelia-bootstrap.bundle.js:15373:19)
    at ResourceModule.initialize (http://localhost:9000/aurelia-bootstrap.bundle.js:15294:15)
    at http://localhost:9000/aurelia-bootstrap.bundle.js:15672:18
End Inner Error Stack
```

It seems that the components library is trying to use a separate aurelia instance than my main application as the components work fine when they are in the main application's repo.

**Expected/desired behavior:**

* **What is the expected behavior?**
I would like the components imported from the external library to run as they would if they were in my application repo.

* **What is the motivation / use case for changing the behavior?**
To keep my small reusable pieces separate from my larger specific pieces.

**Comment by EisenbergEffect** [comment]
Is this coming from inside a test? It looks like you haven't initialize the PAL in the testing environment. Can you provide some more info?

**Comment by itsnatscott** [comment]
No they are real Aurelia components living in a separate repo. We have the repo npm linked to our Aurelia app. I need to get the components to use the same instance of Aurelia as our app.

**Comment by EisenbergEffect** [comment]
I'm having a hard time understanding what the setup is. How are you "running" the components outside of the app? On a related note, please update your Aurelia libs to make sure it's not something we fixed. We had a bunch of releases today.

**Comment by itsnatscott** [comment]
Thank you for your patience, 
I mocked up a simplified version of the issue using aurelia-skeleton
https://github.com/itsnatscott/binding-issue.

**Comment by itsnatscott** [comment]
I guess from your lack of response that I am pretty off target here?

**Comment by EisenbergEffect** [comment]
I was on vacation.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look into this?

**Comment by jdanyow** [comment]
@itsnatscott does the issue reproduce when you manually copy the components into your app's node modules folder (instead of `npm link`)?

**Comment by itsnatscott** [comment]
@EisenbergEffect @jdanyow Thanks for looking into this!
If I copy directly into node modules the SVGAnalyzer error doesn't occur, but the component does not get the bound data either.

**Comment by jonathaneckman** [comment]
This just popped up for me. It only occurs when testing local changes to `aurelia-binding` referenced with `npm link`. I am open to workarounds if you guys have a different way to test local framework changes besides `npm link`.

**Comment by ghost** [comment]
Why is this closed? The issue still exists as @jonathaneckman described it using `npm link`.
